### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by JamesMc86** [NISystemsEngineering/LabVIEW-Modbus-API#2]
Very excited for this! I've had a couple of error handling issues I've wanted to address for a while.

Can you provide a contributing guide? What version of LabVIEW do you want to use? How would you like to recieve contributions?

I'll confirm they are still in the latest version and submit issues for them if so.

**Comment by becega** [comment]
James I am glad you want to collaborate on this repo. I just added the guidelines in the readme. with commit 73e3aa371bb8875da460db56f07d4e5d22716fcb.
Right now we the Repo is in 2014.
