### ISSUE TITLE
TCP Slave Remove Connections Memory Leak

### ISSUE THREAD

**Issue by jacobson3** [NISystemsEngineering/LabVIEW-Modbus-API#3]
In TCP Slave.lvclass:Remove Unused Connections.vi we remove Connection Records which are no longer "Connected?"  but we never close any of these Connection Records references. This leads to a very slow memory leak if using the TCP Slave API when masters continually connected and reconnect. We should do something similar to what is shown below so we don't leak DVR references.

![remove connections](https://user-images.githubusercontent.com/25009788/44362576-08348500-a487-11e8-8254-cfce958b0b31.png)

**Comment by smithed** [comment]
Woops. The fix is as simple as shown, except that the delete should be outside of the IPE structure. Otherwise you are deleting mutexes inside of a mutex which just seems iffy.
